#!/usr/bin/env python3
"""Verify a finished real run and record it in the paper's integrity audit.

    # read-only verification + run record + audit section
    python scripts/finalize_run.py --run outputs/real_harmbench

    # after an independent replication of the same frozen config:
    python scripts/finalize_run.py --run outputs/real_harmbench \
        --replicated-by outputs/real_harmbench_rep2 --set-paper-result

What it enforces
----------------
The manuscript's honesty rule is that a number becomes a paper result only after it is verified
*and* independently reproduced with a frozen config. This script makes that rule executable:

* every expected artefact exists and parses;
* provenance says ``data_source: real``, ``backend`` is not ``dummy``, and the config snapshot is
  complete enough to reproduce (attack kwargs, calibration settings, prompt-length guard);
* the run actually spent judge calls (a warm-cache re-run reports ~0 cost and is not a cold run);
* the attack was not inert (``attack_effect`` > 0), i.e. the comparison can separate methods;
* calibration did not silently fall back (no tau = 1.0 on every method);
* ``--replicated-by`` reproduces the same summary numbers within tolerance.

``--set-paper-result`` refuses to run unless all of the above hold, and the change is made only in
the provenance JSON (never in the CSVs), so the raw measurements stay untouched.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

import numpy as np

EVALUATE_FILES = (
    "real_evaluation_sweep.csv",
    "real_evaluation_summary.csv",
    "real_evaluation_significance.csv",
    "real_theory_analysis.csv",
    "real_isolation_epsilon.csv",
    "real_cost_summary.csv",
    "real_cost_ledger.csv",
    "real_evaluation_provenance.json",
)
ABLATION_FILES = (
    "real_ablation.csv",
    "real_ablation_provenance.json",
)
AUDIT_PATH = Path("audits/result_integrity_audit.md")
RUN_RECORD_DIR = Path("audits/run_records")
BEGIN = "<!-- BEGIN AUTO: RUN RECORDS (generated by scripts/finalize_run.py) -->"
END = "<!-- END AUTO: RUN RECORDS -->"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _read_csv(path: Path) -> list[dict]:
    with path.open("r", encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


def _floats(rows: list[dict], column: str) -> np.ndarray:
    values = []
    for row in rows:
        raw = (row.get(column) or "").strip()
        if raw == "":
            continue
        try:
            values.append(float(raw))
        except ValueError:
            continue
    return np.asarray(values, dtype=float)


def _finite(a: np.ndarray) -> np.ndarray:
    return a[np.isfinite(a)]


def verify(run: Path) -> tuple[list[str], list[str]]:
    """Return (blockers, warnings) for a run directory."""
    blockers: list[str] = []
    warnings: list[str] = []

    if not run.is_dir():
        return [f"{run} is not a directory"], warnings

    is_evaluate = (run / "real_evaluation_provenance.json").exists()
    is_ablation = (run / "real_ablation_provenance.json").exists()
    if not is_evaluate and not is_ablation:
        return [f"{run} has no real_*_provenance.json: nothing to finalize"], warnings

    required = list(ABLATION_FILES) if (is_ablation and not is_evaluate) else list(EVALUATE_FILES)
    if is_ablation and is_evaluate:
        required = list(EVALUATE_FILES) + list(ABLATION_FILES)
    for name in required:
        path = run / name
        if not path.exists():
            blockers.append(f"missing artefact: {name}")
        elif path.stat().st_size == 0 and name.endswith(".csv"):
            warnings.append(f"{name} is empty (0 bytes)")

    prov_path = run / ("real_evaluation_provenance.json" if is_evaluate else "real_ablation_provenance.json")
    prov = json.loads(prov_path.read_text(encoding="utf-8"))
    config = prov.get("config") or {}

    if prov.get("data_source") != "real":
        blockers.append(f"provenance data_source={prov.get('data_source')!r}, expected 'real'")
    if config.get("backend") == "dummy":
        blockers.append("backend=dummy: ground-truth stand-in verdicts must never be reported")
    for key in ("benchmark", "attack", "attack_kwargs", "n_judges", "seed", "isolation"):
        if key not in config:
            warnings.append(f"provenance config snapshot is missing {key!r}")
    if not (prov.get("extra") or {}).get("dataset", {}).get("sha256"):
        warnings.append("dataset sha256 not recorded: the exact benchmark bytes cannot be re-identified")
    if prov.get("is_paper_result"):
        warnings.append("is_paper_result is already true")
    if not prov.get("gpu"):
        warnings.append("provenance records no GPU: was this run on the GPU host?")

    # cost: a reported RQ5 run must have made calls during this run (cold cache).
    cost_path = run / ("real_cost_summary.csv" if is_evaluate else "real_ablation_cost_summary.csv")
    if cost_path.exists():
        rows = _read_csv(cost_path)
        calls = _floats(rows, "calls")
        if calls.size and float(calls.sum()) == 0.0:
            warnings.append(
                "0 judge calls recorded: this run reused a warm cache, so its cost/latency numbers "
                "are not RQ5 evidence (measure RQ5 on a cold cache)"
            )

    if is_evaluate:
        summary = _read_csv(run / "real_evaluation_summary.csv")
        if not summary:
            blockers.append("real_evaluation_summary.csv has no rows")
        else:
            methods = {row.get("method") for row in summary}
            if "no_defense" not in methods:
                warnings.append("no_defense baseline missing from the summary")
            aegis_rows = [r for r in summary if str(r.get("method", "")).startswith("aegis")]
            effects = _floats(aegis_rows, "attack_effect")
            effects = _finite(effects)
            if effects.size and float(effects.max()) == 0.0:
                warnings.append(
                    "attack_effect == 0 for every Aegis rule: the attack never changed a decision, "
                    "so the comparison cannot separate the methods (see experiment.attack_kwargs)"
                )
            asr = _finite(_floats(summary, "asr_uc"))
            if asr.size == 0:
                warnings.append("asr_uc is NaN for every method: check the benchmark label split")
            thresholds = _finite(_floats(aegis_rows, "threshold"))
            if config.get("calibrate") and thresholds.size and np.allclose(thresholds, 1.0):
                blockers.append(
                    "calibration fell back to tau=1.0 for every Aegis rule (block nothing): the "
                    "calibration slice has no benign items. Re-run with calibrate: false or a "
                    "benchmark that carries benign payloads"
                )

    prov_file = run / "real_evaluation_provenance.json"
    if not prov_file.exists() and not (run / "real_ablation_provenance.json").exists():
        warnings.append("no provenance file found to identify the run")
    return blockers, warnings


def compare_replication(run: Path, replica: Path, tol: float = 1e-9) -> tuple[bool, str]:
    """Compare two runs' summary CSVs keyed by (f, method, n_seeds)."""
    a, b = run / "real_evaluation_summary.csv", replica / "real_evaluation_summary.csv"
    if not a.exists() or not b.exists():
        return False, "both runs need real_evaluation_summary.csv to compare"
    rows_a = {(r.get("f"), r.get("method")): r for r in _read_csv(a)}
    rows_b = {(r.get("f"), r.get("method")): r for r in _read_csv(b)}
    if set(rows_a) != set(rows_b):
        return False, f"different (f, method) keys: {sorted(set(rows_a) ^ set(rows_b))[:5]}"
    worst = 0.0
    worst_key = None
    for key, row in rows_a.items():
        for column in ("asr_uc", "orr", "defense_success_rate"):
            try:
                va = float(row.get(column, "nan"))
                vb = float(rows_b[key].get(column, "nan"))
            except (TypeError, ValueError):
                continue
            if np.isnan(va) and np.isnan(vb):
                continue
            delta = abs(va - vb)
            if delta > worst:
                worst, worst_key = delta, (key, column)
    if worst <= tol:
        return True, f"summary CSVs match (max |delta| = {worst:.3g})"
    return False, f"summary CSVs differ: max |delta| = {worst:.3g} at {worst_key} (tol={tol:g})"


def write_run_record(run: Path, record: dict) -> Path:
    RUN_RECORD_DIR.mkdir(parents=True, exist_ok=True)
    path = RUN_RECORD_DIR / f"{record['run_id']}.json"
    path.write_text(json.dumps(record, indent=2, sort_keys=True), encoding="utf-8")
    return path


def update_audit_section(records: list[dict]) -> None:
    """Rewrite the generated block of audits/result_integrity_audit.md (marker-delimited)."""
    lines = [
        "",
        BEGIN,
        "",
        "| run_id | benchmark | backend | seed(s) | artefacts (sha256 recorded) | verified | independent replication | is_paper_result |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for rec in sorted(records, key=lambda r: r["run_id"]):
        lines.append(
            f"| `{rec['run_id']}` | {rec['benchmark']} | {rec['backend']} | {rec['seeds']} | "
            f"{rec['n_artifacts']} | {'yes' if rec['verified'] else 'NO'} | "
            f"{rec.get('replicated_by') or 'not yet'} | {rec['is_paper_result']} |"
        )
    lines += [
        "",
        "Each row is generated by `scripts/finalize_run.py` from the run directory and its "
        "`*_provenance.json`; the per-artefact SHA-256 digests live in `audits/run_records/<run_id>.json`.",
        "`is_paper_result` flips to `true` only when the run passes verification *and* its summary "
        "matches an independent replication (`--replicated-by`).",
        "",
        END,
        "",
    ]
    block = "\n".join(lines)
    if AUDIT_PATH.exists():
        text = AUDIT_PATH.read_text(encoding="utf-8")
    else:
        text = "# Result integrity audit\n"
    if BEGIN in text and END in text:
        head = text.split(BEGIN)[0].rstrip("\n")
        tail = text.split(END, 1)[1]
        text = head + "\n" + block + tail.lstrip("\n")
    else:
        text = text.rstrip("\n") + "\n" + block
    AUDIT_PATH.write_text(text, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Verify a real run and record it in the integrity audit.")
    ap.add_argument("--run", required=True, help="Run output directory (e.g. outputs/real_harmbench).")
    ap.add_argument("--replicated-by", default=None, help="Second run directory (independent repeat).")
    ap.add_argument("--set-paper-result", action="store_true",
                    help="Flip is_paper_result in the provenance JSON; requires a matching replication.")
    ap.add_argument("--tol", type=float, default=1e-9, help="Tolerance for replication comparison.")
    args = ap.parse_args()

    run = Path(args.run)
    blockers, warnings = verify(run)
    provenance_path = run / ("real_evaluation_provenance.json" if (run / "real_evaluation_provenance.json").exists()
                             else "real_ablation_provenance.json")
    prov = json.loads(provenance_path.read_text(encoding="utf-8")) if provenance_path.exists() else {}
    config = prov.get("config") or {}
    run_id = f"{prov.get('run_id', 'run')}_{config.get('benchmark', 'unknown')}"

    replicated_by = None
    if args.replicated_by:
        ok, message = compare_replication(run, Path(args.replicated_by), tol=args.tol)
        print(f"  [{'PASS' if ok else 'FAIL'}] replication: {message}")
        if not ok:
            blockers.append(f"independent replication failed: {message}")
        else:
            replicated_by = str(args.replicated_by)

    print(f"\nFinalize report for {run_id}\n")
    for message in blockers:
        print(f"  [FAIL] {message}")
    for message in warnings:
        print(f"  [WARN] {message}")
    if not blockers and not warnings:
        print("  [PASS] no issues found")

    artifacts = sorted(
        p for p in run.glob("*") if p.is_file() and p.suffix in {".csv", ".json", ".png"}
    )
    record: dict[str, Any] = {
        "run_id": run_id,
        "run_dir": str(run),
        "benchmark": config.get("benchmark"),
        "backend": config.get("backend"),
        "seeds": config.get("n_seeds"),
        "attack": config.get("attack"),
        "attack_kwargs": config.get("attack_kwargs"),
        "calibrate": config.get("calibrate"),
        "max_prompt_chars": config.get("max_prompt_chars"),
        "git_commit": prov.get("git_commit"),
        "created_utc": prov.get("created_utc"),
        "hostname": prov.get("hostname"),
        "dataset": (prov.get("extra") or {}).get("dataset"),
        "verified": not blockers,
        "replicated_by": replicated_by,
        "is_paper_result": bool(prov.get("is_paper_result")),
        "n_artifacts": len(artifacts),
        "blockers": blockers,
        "warnings": warnings,
        "artifacts": {p.name: _sha256(p) for p in artifacts},
    }

    if args.set_paper_result:
        if blockers:
            print("\n  REFUSING --set-paper-result: verification failed.\n", file=sys.stderr)
            return 1
        if not replicated_by:
            print(
                "\n  REFUSING --set-paper-result: pass --replicated-by <second run> so the result "
                "is independently reproduced first (docs/reproducibility.md).\n",
                file=sys.stderr,
            )
            return 1
        prov["is_paper_result"] = True
        provenance_path.write_text(json.dumps(prov, indent=2, sort_keys=True), encoding="utf-8")
        record["is_paper_result"] = True
        print("  [PASS] is_paper_result set to true in the provenance JSON")

    record_path = write_run_record(run, record)
    print(f"\n  run record: {record_path}")
    print("  artefacts hashed:", ", ".join(sorted(record['artifacts'])) or "(none)")

    records = [json.loads(p.read_text(encoding="utf-8")) for p in RUN_RECORD_DIR.glob("*.json")]
    update_audit_section(records)
    print(f"  audit table updated: {AUDIT_PATH}")
    return 1 if blockers else 0


if __name__ == "__main__":
    raise SystemExit(main())
